Repository vidhi1812/E-commerce, pull requests merged in 2024-03, with the labels that each got.

#3 Backend
  server/.env
  server/Config/conn.js
  server/Controller/Auth-controller.js
  server/Middleware/Auth-middleware.js
  server/Middleware/error.js
  server/Middleware/validator.js
  server/Models/Product-model.js
  server/Models/User-Model.js
  server/Routes/Auth-route.js
  server/Validation/Auth-validation.js
  server/package-lock.json
  server/package.json
  server/server.js
Labels: Create

#4 Done backend
  server/Controller/Auth-controller.js
  server/Models/Product-model.js
  server/Models/User-Model.js
  server/Routes/Auth-route.js
  server/Validation/Auth-validation.js
Labels: Create

#7 Frontend
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/Component/Signupform.css
  client/src/Component/Signupform.jsx
  client/src/Component/background.jpg
  client/src/Component/login.jpg
  client/src/Component/loginform.css
  client/src/Component/loginform.jsx
  client/src/Component/navbar.jsx
Labels: Create

#9 Refersh Token Done
  client/src/Assets/Images/login.jpg
  client/src/Assets/css/Signupform.css
  client/src/Assets/css/loginform.css
  client/src/Component/Signupform.jsx
  client/src/Component/background.jpg
  client/src/Component/loginform.jsx
  server/.env
  server/Controller/Auth-controller.js
  server/Middleware/Auth-middleware.js
  server/Models/User-Model.js
Labels: enhancement, Create

#11 fronted ui
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Assets/css/Signupform.css
  client/src/Component/Signupform.jsx
  client/src/Component/loginform.jsx
  client/src/index.js
  client/src/store/store.js
  server/Controller/Auth-controller.js
  server/Models/User-Model.js
  server/Routes/Auth-route.js
  server/server.js
Labels: enhancement, Create

#12 Issue 10
  client/package-lock.json
  client/package.json
  client/src/Assets/Images/ecommerce.jpg
  client/src/Assets/Images/iconcommerece.png
  client/src/Assets/css/landing.css
  client/src/Component/landing.jsx
  client/src/Component/navbar.jsx
Labels: Create

#13 Landing Page
  client/package-lock.json
  client/src/App.js
  client/src/Assets/css/error.css
  client/src/Assets/css/landing.css
  client/src/Assets/css/navbar45.css
  client/src/Component/error.jsx
  client/src/Component/landing.jsx
  client/src/Component/navbar45.jsx
Labels: Create

#14 Issue 4
  client/src/App.js
  client/src/Component/loginform.jsx
  client/src/index.js
  client/src/store/store.js
  server/Controller/Auth-controller.js
  server/Middleware/Auth-middleware.js
  server/Middleware/error.js
  server/Models/User-Model.js
Labels: enhancement, Create

#15 product done
  client/src/App.js
  client/src/Component/Product.jsx
  client/src/Component/landing.jsx
  client/src/Component/loginform.jsx
  client/src/Component/logout.jsx
  client/src/Component/navbar45.jsx
  client/src/store/store.js
  server/Controller/Auth-controller.js
Labels: enhancement, Create

#16 Product_cart
  client/package-lock.json
  client/package.json
  client/src/Assets/css/error.css
  client/src/Assets/css/product.css
  client/src/Component/Product.jsx
  client/src/Component/error.jsx
  client/src/Component/prod_card.jsx
  server/package-lock.json
  server/package.json
Labels: Create

#17 Frontend UI
  client/src/App.js
  client/src/Assets/css/product.css
  client/src/Component/Product.jsx
  client/src/Component/prod_card.jsx
Labels: Create

#19 Issue 10
  client/src/App.js
  client/src/Assets/css/cart.css
  client/src/Assets/css/product.css
  client/src/Component/cart.jsx
  client/src/Component/prod_card.jsx
Labels: Create

#18 product
  client/src/Component/Product.jsx
  server/Controller/Auth-controller.js
Labels: Create

#20 Issue 4
  client/src/App.js
  client/src/Assets/css/cart.css
  client/src/Assets/css/product.css
  client/src/Component/Product.jsx
  client/src/Component/cart.jsx
  client/src/Component/prod_card.jsx
  server/Controller/Auth-controller.js
  server/Models/User-Model.js
Labels: enhancement, Create

#22 Signup Done
  client/src/Component/Signupform.jsx
Labels: enhancement

#24 Some Ui changes
  client/src/App.js
  client/src/Assets/css/cart.css
  client/src/Assets/css/error.css
  client/src/Assets/css/landing.css
  client/src/Assets/css/product.css
  client/src/Component/cart.jsx
  client/src/Component/landing.jsx
  client/src/Component/loginform.jsx
  client/src/Component/navbar45.jsx
  server/Controller/Auth-controller.js
  server/server.js
Labels: enhancement

#25 Issue 5
  server/Models/User-Model.js
Labels: bug

#26 bug resolved
  client/src/Component/Product.jsx
  server/Controller/Auth-controller.js
  server/Models/User-Model.js
Labels: bug

#27 bug
  client/src/Assets/css/cart.css
  client/src/Assets/css/loginform.css
  client/src/Assets/css/product.css
  client/src/Component/Product.jsx
  client/src/Component/Signupform.jsx
  client/src/Component/cart.jsx
  client/src/Component/loginform.jsx
  client/src/Component/logout.jsx
  client/src/index.css
  client/src/store/store.js
  server/Models/User-Model.js
Labels: bug, enhancement, Create

#28 Update model
  server/Controller/Admin-controller.js
  server/Controller/Auth-controller.js
  server/Controller/Seller-controller.js
  server/Middleware/Admin-middleware.js
  server/Middleware/Seller-middleware.js
  server/Models/Seller-Model.js
  server/Models/User-Model.js
  server/Routes/Admin-route.js
  server/Routes/Seller-route.js
  server/package-lock.json
  server/package.json
  server/server.js
Labels: bug, enhancement, Create

#29 Issue 10
  client/src/Assets/css/loginform.css
  client/src/Assets/css/navbar45.css
  client/src/Assets/css/product.css
Labels: enhancement

#30 admin done
  client/src/Component/Signupform.jsx
  client/src/Component/loginform.jsx
  server/Controller/Admin-controller.js
  server/Controller/Auth-controller.js
  server/Middleware/Seller-middleware.js
  server/Models/User-Model.js
  server/Routes/Admin-route.js
  server/Routes/Seller-route.js
  server/server.js
Labels: bug
